version: '3'
services:
  ddns:
    image: muebau/docker-ddns:latest
    restart: always
    environment:
      DDNS_ADMIN_LOGIN: "admin:secret"
      DDNS_DOMAIN: ddns.domain.example
      DDNS_PARENT_NS: ns.domain.example
      DDNS_DEFAULT_TTL: 60
    ports:
      - "53:53"
      - "53:53/udp"
      - "8080:8080"
    volumes:
       - ./bind-data:/var/cache/bind
       - ./database:/root/database